import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TanstackProvider from "@/providers/TanstackProvider";
import Navbar from "@/components/navbar";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    template: "%s - Uberjob app",
    default: "Uberjob app"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <html lang="ru" suppressHydrationWarning className="h-full">
  <body className={`${geistSans.className} antialiased min-h-screen flex flex-col`}>
    <TanstackProvider>
      {/* 1. Навбар теперь сверху всего */}
      <Navbar /> 

      {/* 2. Контейнер для контента */}
      <main className="flex-1 flex flex-col">
        <div className="mx-auto w-full max-w-7xl px-4 sm:px-6 lg:px-8 py-8">
          {children}
        </div>
      </main>

      <Toaster richColors closeButton />
    </TanstackProvider>
  </body>
</html>
  );
}
